### ISSUE TITLE
Gotham's weather

### ISSUE THREAD

**Issue by Fihh** [Ccamm/Previous-Fifth-Domain-Challenges#1]
I think you've started down the wrong path on this challenge.

1. It's the weather of Gotham (Batman's city). Batman has the theme song "nananana Batman" (or better yet "NaNNaNNaNNaN Batman").
2. Each of the 3 weather stations have many NaNs in the data, but the binary representation of the NaNs is inconsistent (The exponent is all 1s, but values in the significand keep changing) which is not what you'd expect in a file generated by numpy.

Full disclosure - whilst not the author of this challenge, I was there when the challenge was written and the assumption was that hints like those above would be released throughout any competition it was used in. (The author is a physicist and this was their first attempt at writing a CTF challenge, having only heard of the concept the day before, so it's a bit rough around the edges)

**Comment by Ccamm** [comment]
Thanks for providing these hints, I am going to update the README so everyone can see it. Honestly, I feel that these hints are vital to do the challenge, so once again I really appreciate you providing it.
